//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCall.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEST_RollCallDBEntities : DbContext
    {
        public TEST_RollCallDBEntities()
            : base("name=TEST_RollCallDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RCS_MEETING> RCS_MEETING { get; set; }
        public virtual DbSet<RCS_CALL_LOG> RCS_CALL_LOG { get; set; }
        public virtual DbSet<RCS_MEMBER> RCS_MEMBER { get; set; }
    }
}
