--這一隻SQL主要是為了處理之前開發批量更新員工名冊的功能給HR時，由於表頭抓取跟HR上傳的文件對不上

--導致全部員工的業屬(SALES_DEP_ID)都變成總經理，因為後端的條件判斷是根據之前OA上的名冊來做

--OA名冊中總經理的"部門"欄位不會有站名資訊，就只有"總經理"，後端條件為如果沒有站名資訊就賦值"總經理"

--因此透過部門(DEPARTMENT)來復原業屬

UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.TPE' WHERE DEPARTMENT LIKE N'%台北沛華%'

UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PC.TPE' WHERE DEPARTMENT LIKE N'%台北沛榮%'

UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.TXG' WHERE DEPARTMENT LIKE N'%台中沛華%'

UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PC.TXG' WHERE DEPARTMENT LIKE N'%台中沛榮%'

UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.KHH' WHERE DEPARTMENT LIKE N'%高雄沛華%'

UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PC.KHH' WHERE DEPARTMENT LIKE N'%高雄沛榮%'

SELECT * FROM RCS_EMPLOYEES WHERE SALES_DEP_ID LIKE N'%總經理%'





UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.TPE' WHERE POSITION LIKE N'%專案企劃經理%'