--這隻SQL是因為抽籤系統曾經因為改版調整過TableSchema，原本就存在的表也刪除部分舊有的欄位

--為了讓舊版系統已經存在的資料 可以還原出來並且寫到新版系統上，並且增加新的資料表與欄位

--因此需要以下一大段SQL才能將舊版的資料庫升級到新版

--現在因為資料庫已經遷移完畢，應該不會用到這隻SQL了，但為了讓後續維護的人更清楚為什麼早期的資料看起來比較不一樣

--故保留這隻SQL指令檔並進行說明
----------------------------------------------------------------------------------------------

-- 一，欄位、條件約束、外鍵關聯異動

--移除RCS_CALL_LOG中的[RCS_MEMBER_UN2]條件約束
ALTER TABLE RCS_CALL_LOG DROP CONSTRAINT RCS_CALL_LOG_UN2;

--RCS_MEMBER中的[RCS_MEMBER_UN2]條件約束與[RCS_MEMBER_FK1]外鍵關聯
ALTER TABLE RCS_MEMBER DROP CONSTRAINT RCS_MEMBER_UN2;
ALTER TABLE RCS_MEMBER DROP CONSTRAINT RCS_MEMBER_FK1;


ALTER TABLE RCS_MEETING ADD LECTURER NVARCHAR(50) NULL; --新增講師欄位到RCS_MEETING中

ALTER TABLE RCS_MEMBER ADD MEETING_GROUP_AUTO_ID BIGINT NULL; --新增會議分組流水號欄位到RCS_MEMBER中
ALTER TABLE RCS_MEMBER ADD EMP_AUTO_ID BIGINT NULL;  -- 新增員工流水號到RCS_MEMBER中

ALTER TABLE RCS_CALL_LOG ADD EMP_AUTO_ID BIGINT NULL; --新增員工流水號到RCS_CALL_LOG中
-- ALTER TABLE RCS_CALL_LOG ADD MEETING_GROUP_AUTO_ID BIGINT NULL; --新增會議分組流水號到RCS_CALL_LOG中


-- 暫不移除舊欄位，但為了新版系統可以寫入新資料，先讓這些欄位可為NULL
ALTER TABLE RCS_MEMBER
ALTER COLUMN MEETING_AUTO_ID bigint NULL;

ALTER TABLE RCS_MEMBER
ALTER COLUMN GROUP_NAME nvarchar(50) NULL;

ALTER TABLE RCS_MEMBER
ALTER COLUMN MEMBER_NAME nvarchar(20) NULL;



---------------------------------------------------------------------------------------------------------------------------------

-- 二，新增資料表

-- 先刪除舊版欄位不完整的資料表RCS_GROUP、RCS_MEETING、RCS_EMPLOYEES  (開發到一半)
DROP TABLE RCS_EMPLOYEES;

DROP TABLE RCS_MEETING_GROUP;

DROP TABLE RCS_GROUP;



-- 員工資料表
CREATE TABLE RCS_EMPLOYEES (
    AUTO_ID BIGINT IDENTITY(1,1) NOT NULL,
    AUTO_GUID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
    EMP_NAME NVARCHAR(20) NOT NULL,
    DEPARTMENT NVARCHAR(50) NOT NULL,
    POSITION NVARCHAR(50) NOT NULL,
    EMP_NUMBER NVARCHAR(10) NOT NULL,
    SALES_DEP_ID NVARCHAR(50) NOT NULL,
    REMARK NVARCHAR(MAX),
    IS_ACTIVED BIT DEFAULT 1 NOT NULL,
    CREATE_BY NVARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    MODIFY_BY NVARCHAR(20) NOT NULL,
    MODIFY_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    IS_DELETED BIT DEFAULT 0 NOT NULL,
    DELETE_BY NVARCHAR(20),
    DELETE_TIME DATETIME2,
    CONSTRAINT RCS_EMPLOYEES_PK PRIMARY KEY (AUTO_ID),
    CONSTRAINT RCS_EMPLOYEES_UN1 UNIQUE (AUTO_GUID),
    CONSTRAINT RCS_EMPLOYEES_UN2 UNIQUE (EMP_NAME,EMP_NUMBER),
);

--常規組別
CREATE TABLE RCS_GROUP (
    AUTO_ID BIGINT IDENTITY(1,1) NOT NULL,
    AUTO_GUID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
    GROUP_NAME NVARCHAR(20) NOT NULL,
    REMARK NVARCHAR(MAX),
    IS_ACTIVED BIT DEFAULT 1 NOT NULL,
    CREATE_BY NVARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    MODIFY_BY NVARCHAR(20) NOT NULL,
    MODIFY_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    IS_DELETED BIT DEFAULT 0 NOT NULL,
    DELETE_BY NVARCHAR(20),
    DELETE_TIME DATETIME2,
    CONSTRAINT RCS_GROUP_PK PRIMARY KEY (AUTO_ID),
    CONSTRAINT RCS_GROUP_UN1 UNIQUE (AUTO_GUID),
);


--員工與常規組別對應表
CREATE TABLE RCS_EMPLOYEE_GROUP (
    AUTO_ID BIGINT IDENTITY(1,1) NOT NULL,
    AUTO_GUID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
    EMP_AUTO_ID BIGINT NOT NULL,
    GROUP_AUTO_ID BIGINT NOT NULL,
    REMARK NVARCHAR(MAX),
    IS_ACTIVED BIT DEFAULT 1 NOT NULL,
    CREATE_BY NVARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    MODIFY_BY NVARCHAR(20) NOT NULL,
    MODIFY_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    IS_DELETED BIT DEFAULT 0 NOT NULL,
    DELETE_BY NVARCHAR(20),
    DELETE_TIME DATETIME2,
    CONSTRAINT RCS_EMPLOYEE_GROUP_PK PRIMARY KEY (AUTO_ID),
    CONSTRAINT RCS_EMPLOYEE_GROUP_FK1 FOREIGN KEY (EMP_AUTO_ID) REFERENCES RCS_EMPLOYEES(AUTO_ID),
    CONSTRAINT RCS_EMPLOYEE_GROUP_FK2 FOREIGN KEY (GROUP_AUTO_ID) REFERENCES RCS_GROUP(AUTO_ID),
    CONSTRAINT RCS_EMPLOYEE_GROUP_UN1 UNIQUE (AUTO_GUID),
    CONSTRAINT RCS_EMPLOYEE_GROUP_UN2 UNIQUE (EMP_AUTO_ID,GROUP_AUTO_ID),
);



--會議組別
CREATE TABLE RCS_MEETING_GROUP (
    AUTO_ID BIGINT IDENTITY(1,1) NOT NULL,
    AUTO_GUID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
    MEETING_AUTO_ID BIGINT NOT NULL,
    GROUP_NAME NVARCHAR(20) NOT NULL,
    REMARK NVARCHAR(MAX),
    IS_ACTIVED BIT DEFAULT 1 NOT NULL,
    CREATE_BY NVARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    MODIFY_BY NVARCHAR(20) NOT NULL,
    MODIFY_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    IS_DELETED BIT DEFAULT 0 NOT NULL,
    DELETE_BY NVARCHAR(20),
    DELETE_TIME DATETIME2,
    CONSTRAINT RCS_MEETING_GROUP_PK PRIMARY KEY (AUTO_ID),
    CONSTRAINT RCS_MEETING_GROUP_FK1 FOREIGN KEY (MEETING_AUTO_ID) REFERENCES RCS_MEETING(AUTO_ID),
    CONSTRAINT RCS_MEETING_GROUP_UN1 UNIQUE (AUTO_GUID),
);

--會議組別與常規組別對應表
CREATE TABLE RCS_MEETING_GROUP_MAP (
    AUTO_ID BIGINT IDENTITY(1,1) NOT NULL,
    AUTO_GUID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
    GROUP_AUTO_ID BIGINT NOT NULL,
    MEETING_GROUP_AUTO_ID BIGINT NOT NULL,
    REMARK NVARCHAR(MAX),
    IS_ACTIVED BIT DEFAULT 1 NOT NULL,
    CREATE_BY NVARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    MODIFY_BY NVARCHAR(20) NOT NULL,
    MODIFY_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    IS_DELETED BIT DEFAULT 0 NOT NULL,
    DELETE_BY NVARCHAR(20),
    DELETE_TIME DATETIME2,
    CONSTRAINT RCS_MEETING_GROUP_MAP_PK PRIMARY KEY (AUTO_ID),
    CONSTRAINT RCS_MEETING_GROUP_MAP_FK1 FOREIGN KEY (GROUP_AUTO_ID) REFERENCES RCS_GROUP(AUTO_ID),
    CONSTRAINT RCS_MEETING_GROUP_MAP_FK2 FOREIGN KEY (MEETING_GROUP_AUTO_ID) REFERENCES RCS_MEETING_GROUP(AUTO_ID),
    CONSTRAINT RCS_MEETING_GROUP_MAP_UN1 UNIQUE (AUTO_GUID),
    CONSTRAINT RCS_MEETING_GROUP_MAP_UN2 UNIQUE (MEETING_GROUP_AUTO_ID,GROUP_AUTO_ID),
);
---------------------------------------------------------------------------------------------------------------------------------
-- 三，修復資料

-- 新版系統需要登入，目前有三組個別給北中高HR使用的帳號
-- 台北HR 帳號：testTPEHR 密碼 abcd1234
-- 台中HR 帳號：testTXGHR 密碼 abcd1234
-- 高雄HR 帳號：testKHHHR 密碼 abcd1234
-- 如需註冊新帳號，可以進入Account/Register，但權限欄位需要寫'台北HR'、'台中HR'、'高雄HR'其中一種

-- 1.先在新版系統中上傳名冊，執行專案後進入RCS_EMPLOYEES/UploadEmployeeList上傳名冊(專案Content/files底下有)

-- 2.用MEMBER_NAME比對員工姓名，指派員工流水號到RCS_MEMBER的EMP_AUTO_ID中
UPDATE RCS_MEMBER
SET EMP_AUTO_ID = RCS_EMPLOYEES.AUTO_ID
FROM RCS_EMPLOYEES
WHERE MEMBER_NAME = RCS_EMPLOYEES.EMP_NAME

-- 3.從RCS_MEMBER的AUTO_ID關聯RCS_CALL_LOG中的MEMBER_AUTO_ID
-- 再根據"RCS_EMPLOYEES的EMP_NAME"查詢出與"RCS_MEMBER的MEMBER_NAME"相同的員工流水號指派到RCS_CALL_LOG新增的EMP_AUTO_ID欄位
UPDATE RCS_CALL_LOG
SET EMP_AUTO_ID = E.AUTO_ID
FROM RCS_CALL_LOG AS C
INNER JOIN RCS_MEMBER AS M ON C.MEMBER_AUTO_ID = M.AUTO_ID
INNER JOIN RCS_EMPLOYEES AS E ON M.MEMBER_NAME = E.EMP_NAME
WHERE C.EMP_AUTO_ID IS NULL

-- 4.用RCS_MEMBER的MEETING_AUTO_ID與GROUP_NAME來新增舊版的會議資料到MEETING_GROUP(會議組別)中，因為新版抽籤記錄需要從會議組別找出組別名稱
INSERT INTO RCS_MEETING_GROUP (MEETING_AUTO_ID, GROUP_NAME, IS_ACTIVED, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME)
SELECT 
    M.MEETING_AUTO_ID,
    M.GROUP_NAME,
    1 AS IS_ACTIVED,
    'System' AS CREATE_BY,
    GETDATE() AS CREATE_TIME,
    'System' AS MODIFY_BY,
    GETDATE() AS MODIFY_TIME
FROM RCS_MEMBER AS M
LEFT JOIN RCS_MEETING_GROUP AS MG
    ON M.MEETING_AUTO_ID = MG.MEETING_AUTO_ID
    AND M.GROUP_NAME = MG.GROUP_NAME
WHERE MG.AUTO_ID IS NULL
GROUP BY M.MEETING_AUTO_ID, M.GROUP_NAME

-- 5.以RCS_MEETING_GROUP的新增的舊版會議資料根據會議流水號與組別名稱進行關聯，因為新版RCS_MEMBER多了會議組別流水號
-- 將會議用分組的流水號增加到RCS_MEMBER新增的MEETING_GROUP_AUTO_ID欄位中
UPDATE RCS_MEMBER
SET RCS_MEMBER.MEETING_GROUP_AUTO_ID = MG.AUTO_ID
FROM RCS_MEMBER
INNER JOIN RCS_MEETING_GROUP AS MG
    ON RCS_MEMBER.MEETING_AUTO_ID = MG.MEETING_AUTO_ID
    AND RCS_MEMBER.GROUP_NAME = MG.GROUP_NAME
WHERE RCS_MEMBER.MEETING_GROUP_AUTO_ID IS NULL

-- 6.以RCS_MEMBER的EMP_AUTO_ID關聯RCS_CALL_LOG中的EMP_AUTO_ID，因為新版抽籤記錄改為記錄"會議組別流水號"
-- 再以RCS_MEMBER的MEETING_AUTO_ID和GROUP_NAME關聯會議用分組的MEETING_AUTO_ID與GROUP_NAME
UPDATE CL
SET CL.MEETING_GROUP_AUTO_ID = MG.AUTO_ID
FROM RCS_CALL_LOG AS CL
INNER JOIN RCS_MEMBER AS M
    ON CL.MEMBER_AUTO_ID = M.AUTO_ID
INNER JOIN RCS_MEETING_GROUP AS MG
    ON M.MEETING_AUTO_ID = MG.MEETING_AUTO_ID
    AND M.GROUP_NAME = MG.GROUP_NAME
WHERE CL.MEETING_GROUP_AUTO_ID IS NULL

-- 7.個案處理
-- 離職人員(已加入名冊，可以略過)
SELECT * FROM RCS_EMPLOYEES WHERE EMP_NAME LIKE N'%彭郁慈、何沛璇%'

--原始名單名字打錯
UPDATE RCS_MEMBER SET MEMBER_NAME = '徐郁琁' WHERE MEMBER_NAME = '徐郁璇'
UPDATE RCS_MEMBER SET MEMBER_NAME = '陳佳君' WHERE MEMBER_NAME = '陳妍君'
UPDATE RCS_MEMBER SET MEMBER_NAME = '陳奕君' WHERE MEMBER_NAME = '陳羿君'
UPDATE RCS_MEMBER SET MEMBER_NAME = '黃閔熙' WHERE MEMBER_NAME = '黃敏熙'

-- 查出被抽到的會議成員流水號和名字
SELECT DISTINCT MEMBER_AUTO_ID, GROUP_NAME,MEMBER_NAME, RCS_CALL_LOG.CREATE_TIME
FROM RCS_CALL_LOG 
LEFT JOIN RCS_MEMBER
ON RCS_MEMBER.AUTO_ID = RCS_CALL_LOG.MEMBER_AUTO_ID
WHERE RCS_MEMBER.CREATE_TIME > '2024/10/15' AND MEMBER_NAME LIKE N'%%'
AND RCS_MEMBER.MEETING_AUTO_ID NOT IN (178,179,185,188,189,191)




-- 查被抽到的新進或離職人員或是名字打錯字的員工
SELECT DISTINCT MEMBER_AUTO_ID, GROUP_NAME ,MEMBER_NAME , RCS_CALL_LOG.CREATE_TIME
FROM RCS_CALL_LOG 
LEFT JOIN RCS_MEMBER
ON RCS_MEMBER.AUTO_ID = RCS_CALL_LOG.MEMBER_AUTO_ID
WHERE RCS_MEMBER.CREATE_TIME > '2024/10/15' AND MEMBER_NAME LIKE N'%%' AND RCS_MEMBER.EMP_AUTO_ID IS NULL
AND RCS_MEMBER.MEETING_AUTO_ID NOT IN (178,179,185,188,189,191) --這幾筆為假資料的流水號

--查總經理業屬
SELECT * FROM RCS_EMPLOYEES WHERE SALES_DEP_ID LIKE N'%總經理%'


--更新總經理業屬
UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.PTE' WHERE EMP_NAME = '劉曜誠'
UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.PTE' WHERE EMP_NAME = '楊曜州'
UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.TXG' WHERE EMP_NAME = '胡志宏'
UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PC.TXG' WHERE EMP_NAME = '徐明鴻'
UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.KHH' WHERE EMP_NAME = '高美如'
UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PC.KHH' WHERE EMP_NAME = '楊宏緒'
UPDATE RCS_EMPLOYEES SET SALES_DEP_ID = 'PS.PTE' WHERE EMP_NAME = '汪秋月'


-- 8.復原完成後直接再次執行步驟2、3即可在抽籤記錄撈到缺失的資料

------------------------------------------------------------------------------------------------------------------------

-- 四、使用新版後可能需要處理的內容

-- 查有加入會議的新進或離職人員
SELECT DISTINCT MEMBER_NAME,GROUP_NAME,MEETING_NAME,RCS_MEETING.CREATE_TIME
FROM RCS_MEETING
LEFT JOIN RCS_MEMBER
ON MEETING_AUTO_ID = RCS_MEETING.AUTO_ID
WHERE EMP_AUTO_ID IS NULL AND RCS_MEETING.CREATE_TIME > '2024/10/15' AND MEETING_AUTO_ID NOT IN (178,179,185,188,189,191)--這幾筆為假資料的流水號


-- 調整員工資料CREATE_BY欄位

UPDATE RCS_EMPLOYEES SET CREATE_BY = '高雄HR' WHERE SALES_DEP_ID LIKE N'%KHH%'
UPDATE RCS_EMPLOYEES SET CREATE_BY = '台中HR' WHERE SALES_DEP_ID LIKE N'%TXG%'

-- 刪除測試資料

UPDATE RCS_MEETING SET IS_DELETED = 1 WHERE CREATE_TIME < '2024/10/15'

UPDATE RCS_MEETING SET IS_DELETED = 1 WHERE MEETING_NAME LIKE N'%測試%'

UPDATE RCS_MEETING SET IS_DELETED = 1 WHERE MEETING_NAME LIKE N'%今天%'

UPDATE RCS_MEETING SET IS_DELETED = 1 WHERE AUTO_ID = 179


-------------------------------------------------------------------------------------------------------------

-- 五、新版系統可以正常使用後，關聯和欄位調整

-- 1.使必要欄位不得為空
ALTER TABLE RCS_MEMBER
ALTER COLUMN MEETING_GROUP_AUTO_ID BIGINT NOT NULL;

UPDATE RCS_MEMBER SET EMP_AUTO_ID = 743 WHERE EMP_AUTO_ID IS NULL -- 需指派某筆新建的假資料值到過去所有假資料的欄位中使所有資料都不為空
																  -- 否則下面那一段會無法執行(因為有空的EMP_AUTO_ID)
ALTER TABLE RCS_MEMBER
ALTER COLUMN EMP_AUTO_ID BIGINT NOT NULL;

-- 2.建立新版系統使用的外鍵關聯
ALTER TABLE RCS_CALL_LOG ADD CONSTRAINT RCS_CALL_LOG_FK1 FOREIGN KEY (EMP_AUTO_ID) REFERENCES RCS_EMPLOYEES(AUTO_ID)
ALTER TABLE RCS_CALL_LOG ADD CONSTRAINT RCS_CALL_LOG_FK2 FOREIGN KEY (MEETING_GROUP_AUTO_ID) REFERENCES RCS_MEETING_GROUP(AUTO_ID)

ALTER TABLE RCS_MEMBER ADD CONSTRAINT RCS_MEMBER_FK1 FOREIGN KEY (EMP_AUTO_ID) REFERENCES RCS_EMPLOYEES(AUTO_ID)
ALTER TABLE RCS_MEMBER ADD CONSTRAINT RCS_MEMBER_FK2 FOREIGN KEY (MEETING_GROUP_AUTO_ID) REFERENCES RCS_MEETING_GROUP(AUTO_ID)

-- 3.移除舊版系統使用的欄位
ALTER TABLE RCS_MEMBER DROP COLUMN MEETING_AUTO_ID;
ALTER TABLE RCS_MEMBER DROP COLUMN GROUP_NAME;
ALTER TABLE RCS_MEMBER DROP COLUMN MEMBER_NAME;

----------------------------------------------------------------------------------------------------------------

-- 六、備份會議成員資料

-- 1.建立備份資料表

CREATE TABLE RCS_MEMBER_BACKUP (
    AUTO_ID BIGINT IDENTITY(1,1) NOT NULL,
	AUTO_GUID UNIQUEIDENTIFIER NOT NULL,   
    MEETING_GROUP_AUTO_ID BIGINT NOT NULL, 
    EMP_AUTO_ID BIGINT NOT NULL,
	BACKUP_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
    BACKUP_REASON NVARCHAR(MAX),
    REMARK NVARCHAR(MAX),
    IS_ACTIVED BIT NOT NULL,            
    IS_DELETED BIT NOT NULL,            
    CREATE_BY NVARCHAR(20) NOT NULL,     
    CREATE_TIME DATETIME2 NOT NULL,     
    MODIFY_BY NVARCHAR(20) NOT NULL,    
    MODIFY_TIME DATETIME2 NOT NULL,     
    DELETE_BY NVARCHAR(20),             
    DELETE_TIME DATETIME2, 
    CONSTRAINT RCS_MEMBER_BACKUP_PK PRIMARY KEY (AUTO_ID)
);

-- 2.建立備份SP

CREATE PROCEDURE BackupRCSMember
    @MeetingGroupId BIGINT,
    @BackupReason NVARCHAR(MAX)
AS
BEGIN
    BEGIN TRY
        -- 插入尚未備份的資料
        INSERT INTO RCS_MEMBER_BACKUP (
            AUTO_GUID,
            MEETING_GROUP_AUTO_ID,
            EMP_AUTO_ID,
            REMARK,
            IS_ACTIVED,
            CREATE_BY,
            CREATE_TIME,
            MODIFY_BY,
            MODIFY_TIME,
            IS_DELETED,
            DELETE_BY,
            DELETE_TIME,
            BACKUP_REASON,
            BACKUP_TIME
        )
        SELECT 
            NEWID(),
            MEETING_GROUP_AUTO_ID,
            EMP_AUTO_ID,
            REMARK,
            IS_ACTIVED,
            CREATE_BY,
            CREATE_TIME,
            MODIFY_BY,
            MODIFY_TIME,
            IS_DELETED,
            DELETE_BY,
            DELETE_TIME,
            @BackupReason,
            GETDATE()
        FROM RCS_MEMBER AS RM
        WHERE RM.MEETING_GROUP_AUTO_ID = @MeetingGroupId
          AND NOT EXISTS (
              SELECT 1 
              FROM RCS_MEMBER_BACKUP AS RMB
              WHERE RMB.MEETING_GROUP_AUTO_ID = RM.MEETING_GROUP_AUTO_ID
                AND RMB.EMP_AUTO_ID = RM.EMP_AUTO_ID
          );

        PRINT '備份寫入成功';
    END TRY
    BEGIN CATCH
        PRINT '備份失敗: ' + ERROR_MESSAGE();
    END CATCH
END;



-- 3.建立排程SP

CREATE PROCEDURE ScheduleMemberBackup
AS
BEGIN
    BEGIN TRY
        -- 宣告變數
        DECLARE @MeetingGroupId BIGINT;
        DECLARE @BackupReason NVARCHAR(255);

        -- 查詢需要備份的會議分組
        DECLARE meeting_cursor CURSOR FOR
        SELECT MEETING_GROUP.AUTO_ID, '會議結束自動備份'
        FROM RCS_MEETING_GROUP AS MEETING_GROUP
        JOIN RCS_MEETING AS MEETING ON MEETING_GROUP.MEETING_AUTO_ID = MEETING.AUTO_ID
        WHERE MEETING.MEETING_END < GETDATE() AND MEETING.IS_DELETED = 0;

        OPEN meeting_cursor;
        FETCH NEXT FROM meeting_cursor INTO @MeetingGroupId, @BackupReason;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            -- 呼叫備份SP
            EXEC BackupRCSMember @MeetingGroupId = @MeetingGroupId, @BackupReason = @BackupReason;
            FETCH NEXT FROM meeting_cursor INTO @MeetingGroupId, @BackupReason;
        END;

        CLOSE meeting_cursor;
        DEALLOCATE meeting_cursor;

        PRINT '備份排程完成';
    END TRY
    BEGIN CATCH
        PRINT '備份發生錯誤: ' + ERROR_MESSAGE();
    END CATCH
END;


EXEC ScheduleMemberBackup

-- SQL Server Agent 定期呼叫 ScheduleMemberBackup

